export const Coffees = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    types: ['TRADICIONAL'],
    price: 990,
    imageUrl: '../src/assets/coffes/expresso.png',
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    types: ['TRADICIONAL'],
    price: 990,
    imageUrl: '../src/assets/coffes/americano.png',
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    types: ['TRADICIONAL'],
    price: 990,
    imageUrl: '../src/assets/coffes/expressoCremoso.png',
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    types: ['TRADICIONAL', 'GELADO'],
    price: 990,
    imageUrl: '../src/assets/coffes/caféGelado.png',
  },
  {
    id: 5,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/caféComLeite.png',
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/latte.png',
  },
  {
    id: 7,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/capuccino.png',
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/macchiato.png',
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/mochaccino.png',
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    types: ['ESPECIAL', 'COM LEITE'],
    price: 990,
    imageUrl: '../src/assets/coffes/chocolateQuente.png',
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    types: ['ALCOÓLICO', 'ESPECIAL', 'GELADO'],
    price: 990,
    imageUrl: '../src/assets/coffes/Cubano.png',
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    types: ['ESPECIAL'],
    price: 990,
    imageUrl: '../src/assets/coffes/havaiano.png',
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    types: ['ESPECIAL'],
    price: 990,
    imageUrl: '../src/assets/coffes/árabe.png',
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    types: ['ESPECIAL', 'ALCOÓLICO'],
    price: 990,
    imageUrl: '../src/assets/coffes/irlandês.png',
  },
]
